@startuml Ambientes Internos
' Configurações
skinparam classAttributeIconSize 0
hide empty members
left to right direction

' ---------- ENUMS GERAIS ----------
enum Abertura
enum MaterialEsquadria
enum Revestimento
enum TipoParede
enum TipoPiso
enum TipoTeto
enum TipoEquipamento
enum TipoInstalacaoEletrica
enum TipoInstalacaoLogica
enum TipoInstalacaoHidrossanitaria
enum TipoLampada
enum FormatoLampada
enum FixacaoLuminaria
enum MaterialLuminaria
enum MaterialPeitoril

' ---------- ENUMS DE EXTINTOR (NOVO) ----------
enum TipoExtintor {
    AGUA
    CO2
    PO_QUIMICO
    OUTRO
}
enum ClasseIncendio {
    A
    B
    C
    D
    K
}


' ---------- GEOMETRIA ----------
abstract class Geometria {
  + id: Long?
  + base: BigDecimal
  + altura: BigDecimal
  + repeticao: Int
  --
  + {abstract} calcularAreaM2(): BigDecimal
  + calcularAreaTotalM2(): BigDecimal
}
class Retangular extends Geometria
class Triangular extends Geometria


' ---------- CLASSE AMBIENTE ----------
abstract class Ambiente {
  + id: Long?
  + nome: String
  + localizacao: String
  + capacidade: Int
  + informacaoAdicional: String
  --
  + calcularAreaParedesM2(): BigDecimal
  + calcularAreaPisosM2(): BigDecimal
  + calcularAreaPortasM2(): BigDecimal
  + calcularAreaJanelasM2(): BigDecimal
  + calcularCargaAmbiente(): BigDecimal
}


' ---------- HIERARQUIA DE ELEMENTOS CONSTRUTIVOS ----------
abstract class ElementoConstrutivo {
  + id: Long?
  + quantidade: Int
  + informacaoAdicional: String
  --
  + calcularAreaTotal(): BigDecimal
}
class Parede extends ElementoConstrutivo {
  + tipo: TipoParede
  + revestimento: Revestimento
}
class Piso extends ElementoConstrutivo {
  + tipo: TipoPiso
}
class Teto extends ElementoConstrutivo {
  + tipo: TipoTeto
  + revestimento: Revestimento
}


' ---------- HIERARQUIA DE ESQUADRIAS (PADRÃO COMPOSITE) ----------
abstract class Esquadria {
  + id: Long?
  + informacaoAdicional: String
  --
  + obterQuantidadeFolhas(): Int
  + calcularAreaFolhasM2(): BigDecimal
  ' ... outros métodos ...
}
class Porta extends Esquadria {
 + calcularVaoUtil(): BigDecimal
}
class Janela extends Esquadria {
}

abstract class ComponenteEsquadria {
  + id: Long?
  + material: MaterialEsquadria
  + informacaoAdicional: String
}
class Folha extends ComponenteEsquadria {
  + abertura: Abertura
}
class Bandeirola extends ComponenteEsquadria {
  + abertura: Abertura
}
class Guarnicao extends ComponenteEsquadria {
  + espessura: BigDecimal
}

class Peitoril {
  + id: Long?
  + altura: BigDecimal
  + material: MaterialPeitoril
  + informacaoAdicional: String
}


' ---------- HIERARQUIA DE COMPONENTES ----------
abstract class Componente {
  + id: Long?
  + quantidade: Int
  + informacaoAdicional: String
}
abstract class ComponenteEletrico extends Componente {
  + {abstract} calcularPotenciaWatts(): BigDecimal
}
class Equipamento extends ComponenteEletrico {
  + tipo: TipoEquipamento
  + potenciaWatts: BigDecimal
}
class Luminaria extends ComponenteEletrico {
  + material: MaterialLuminaria
  + fixacao: FixacaoLuminaria
  + quantidadeLampadas: Int
  + aletada: Boolean
  --
  + calcularPotenciaLuminariaWatts(): BigDecimal
}
class Lampada {
    + id: Long?
    + tipo: TipoLampada
    + formato: FormatoLampada
    + potenciaWatts: BigDecimal
}
class InstalacaoEletrica extends Componente {
    + tipo: TipoInstalacaoEletrica
    + capacidade: BigDecimal
    + unidadeCapacidade: String
}
class InstalacaoLogica extends Componente {
    + tipo: TipoInstalacaoLogica
}
class InstalacaoHidrossanitaria extends Componente {
    + tipo: TipoInstalacaoHidrossanitaria
    + pontoHidraulico: Int
    + pontoSanitario: Int
}
class Extintor extends Componente {
    + capacidade: String
    + unidadeCapacidade: String
    + tipo: TipoExtintor
}


' ---------- RELACIONAMENTOS ----------
' Herança
Componente <|-- Extintor

' Ambiente com seus Elementos
Ambiente "1" *-- "0..*" Piso : - pisos
Ambiente "1" *-- "0..*" Parede : - paredes
Ambiente "1" *-- "0..*" Teto : - tetos
Ambiente "1" *-- "0..*" Porta : - portas
Ambiente "1" *-- "0..*" Janela : - janelas
Ambiente "1" *-- "0..*" Componente : - componentes
Ambiente "1" *-- "0..*" ComponenteEletrico : - componentesEletricos

' Composição com Geometria
ElementoConstrutivo "1" *-- "1..*" Geometria : - geometrias
Esquadria "1" *-- "1" Geometria : - geometria
ComponenteEsquadria "1" *-- "1" Geometria : - geometria
Peitoril "1" *-- "1" Geometria : - geometria

' Composição de Esquadria
Esquadria "1" *-- "0..*" ComponenteEsquadria : - componentes
Janela "1" *-- "1" Peitoril : - peitoril

' Composição de Luminaria
Luminaria "1" *-- "1" Lampada : - lampada

' Associações com Enums
Parede -- TipoParede
Parede -- Revestimento
Piso -- TipoPiso
Teto -- TipoTeto
Teto -- Revestimento
ComponenteEsquadria -- MaterialEsquadria
Folha -- Abertura
Bandeirola -- Abertura
Peitoril -- MaterialPeitoril
Equipamento -- TipoEquipamento
Lampada -- TipoLampada
Lampada -- FormatoLampada
Luminaria -- MaterialLuminaria
Luminaria -- FixacaoLuminaria
InstalacaoEletrica -- TipoInstalacaoEletrica
InstalacaoLogica -- TipoInstalacaoLogica
InstalacaoHidrossanitaria -- TipoInstalacaoHidrossanitaria
Extintor -- TipoExtintor
Extintor "1" *-- "1..*" ClasseIncendio : - classesIncendio
@enduml